import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { headers } from "next/headers";
import Footer from "@/components/landing/footer";
import { auth } from "@/lib/auth";
import { Toaster } from "react-hot-toast"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch session server-side and pass to Navbar so it can render correctly
  const session = await auth.api.getSession({ headers: await headers() });

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Navbar session={session} />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
